### ISSUE TITLE
Oprava úkolu 

### ISSUE THREAD

**Issue by ifischerova** [VeronikaGabrielova/Prvni_ukol#1]
Ahoj Verčo, posílám zpětnou vazbu na první úkol. Něco je přímo k opravení (u toho jsou checkboxy), něco jsou spíš tipy a best practices a je spíš na Tobě, jestli to upravíš :-) 

### index.html
- [x] Je třeba celý dokument zformátovat, aby jednotlivé tagy byly správně zanořené.

**alt texty u profilové fotografie + ikonky** 
- Alt text by měl co nejvíce vystihovat obsah/informaci obsažené ve fotce či ikonce. Pokud má obrázek spíš dekorativní formu, tak je alt text nadbytečný a nepřidává se. Alt text totiž není jen text, který se zobrazí při nenačtení obrázku/ikonky, ale zároveň ho čtou čtečky pro nevidomé uživatele webu. 
Takže v tomto konkrétním případě by například u profilové fotografie mohlo být "profilová fotografie Veroniky Gabrielové". Pokud jde o ikonky, tak třeba ty v headeru bych řešila tak, že ikonka telefonu by měla alt text "ikonka telefonu", ikonka lokace by měla alt text "adresa", ale další dvě by byly bez alt textu, protože je vedle nich ještě text o co se jedná "email", "facebook".
- [x] alt texty u fotografie a ikonek

**Obrázky**
- obrázek by neměl být součástí nadpisu, ale pozicován vedle něj. 
- best practice je řešit velikost obrázků či ikonek prostřednictvím CSS.
- [x] pokud je to takto v HTML, tak se neuvadějí jednotky, protože se defaultně jedná o pixely.

**CSS třídy**
 - [x] určitě doporučuju sjednotit jazyk pro názvy CSS tříd (buď anglicky, nebo česky)

### style.css
- Ideálně by CSS třídy měly jít za sebou tak, jak jsou v HTML.  Nejdřív je dobré nastylovat nějaké globální věci, jako např. body a pak jednotlivé tagy či třídy.  
- height: 100% je dost ošemetná věc, protože tato vlastnost určuje výšku v rámci nadřazeného prvku. Velmi často je ale výška nadřazeného prvku závislá na výšce vnořeného prvku/vnořených prvků. Vzniká tam tak cyklická závislost.

- [x] a:hover by u sebe mělo mít vždy i pseudotřídu :focus - díky ní se link chová vizuelně stejně jako při najetí myší i v případě, že se po stránce pohybuješ pomocí klávesnice.  
- [x] i jednu vlastnost je lepší v selektoru zalomit (a:hover)
- [x] pozor na zarovnání vlastností v selektoru (např. .zajmy ul)
- [x] selektor p footer se zdá být špatně odsazený. 

Vím, že těch videí máte už tak dost, ale kdybys měla čas a chuť posílám tipy na dvě videa k organizaci CSS souborů od mého oblíbeného online lektora na CSS (dohromady je to cca 40 min):

 [The 6 most important CSS concepts for beginners](https://www.youtube.com/watch?v=JnTPd9G6hoY)
 [Improve your CSS by organizing your properties](https://www.youtube.com/watch?v=3Y03OSNw6zo)

**Comment by VeronikaGabrielova** [comment]
Ahoj Ivčo, úkol opraven. Mockrát díky za opravu a tipy jak se zlepšit :-) Na videa určitě mrknu!

**Comment by ifischerova** [comment]
Ahoj Verčo, bezva práce 👍
